services:
  backend:
    build: ./backend
    container_name: ColorMask-backend
    ports:
      - "9000:9000"
    volumes:
      - backend_data:/storage

  frontend:
    build: ./frontend
    container_name: ColorMask-frontend
    ports:
      - "80:80"

volumes:
  backend_data: